### PR TITLE
Marble diagram generation

### PR DESCRIPTION
**Pull request by sengmann**
I added the marble diagram generation inspired by the original rxjs repository. At the moment I have added a few low hanging fruit diagrams. Feel free to contribute the missing diagrams. 

Generate diagrams with `npm run tests2png`. Typedoc can use the images when using a html image tag. All diagrams that I have implemented yet are included in Typedoc comments. 

Still I have one issues:
- The diagram `src/operators/map-to-value-and-changed-properties.test.diagram.ts` shows only the operator but no source or resulting observable. This could be related to `spec/helpers/observableMatcher.ts`

### CODE REVIEW

**Comment by sengmann** [comment]
I have solved the issue where we need extra files to generate the diagrams

**Comment by sengmann** [comment]
The diagram generation in the RxJS 6 repository is broken, when using TestScheduler.run(). Then is only the operator drawn, but no observables. We could fix it for us. The Rx Team moved on to [Swirly](https://github.com/timdp/swirly). This tool uses text diagrams as an input, not the actual test code. In my opinion the diagrams generated by Swirly are much prettier. But the generation from actual test code is so much more developer friendly.

What do you guys think?

I will provide an example with Swirly in this PR to compare the diagrams

**Comment by sengmann** [comment]
An example generated with the Swirly online editor: 
diagram

The code
```
[styles]
event_radius = 70
frame_width = 140

-a---b---c--|

---d---e---f---|

> combineLatestToMap({A: x, B: y})

---g-h-i-j-k---|
g := { A: "a", B: "d" }
h := { A: "b", B: "d" }
i := { A: "b", B: "e" }
j := { A: "c", B: "e" }
k := { A: "c", B: "f" }
```

**Comment by sengmann** [comment]
I just added examples with swirly. To build swirly diagrams run in project root: `npm run build:marbles`. The diagrams are generated in `tmp/swirly/svgs` but are not yet used in documentation

**Comment by pburgmer** [comment]
Hi Sascha,

Looks really promising. Unfortunately I'm currently not able to invest time to rx-ninja :(

**Pull request merged**
